# Generated by Django 3.1.6 on 2021-04-04 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firebase_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='imageURL',
            field=models.URLField(default=None, max_length=2033),
        ),
    ]
